import { Locale } from '@/i18n.config';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './components/header';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Header lang={params.lang}></Header>
        <main>{children}</main>
      </body>
    </html>
  );
}
